# Site
version: 2

# Personal info
name: Marcus Levy
title: IT Support Specialist
email: madlevy88@gmail.com

# Social links
twitter_username: marcuslevy88
github_username:  malevy88
# dribbble_username:
# facebook_username:
# flickr_username:
#instagram_username: 
linkedin_username: www.linkedin.com/in/marcus-levy-54877953
# pinterest_username:
# youtube_username:

# About Section
# about_title: About Me
about_profile_image: /images/me.JPG
about_content: |
  Hi, my name is Marcus Levy, I'm a tech support administrator with over 8 years experience.
  I am currently working for Nicolet High School as an IT Support Specialist with an emphasis on Apple endpoint deployment and administration.

  I am currently studying for my AZ-104 certifcation, as I am looking to move into a system/cloud administrator role. 
  Other plans include getting my CCNA certification, as well as LPIC-1 and 2.
  The things and tools that I currently have the most (recent) experience working with are:
  <mark>MacOS & iOS</mark>,
  <mark>Jamf Pro</mark>,
  <mark>Azure</mark>,
  <mark>Bash</mark> and
  <mark>Python (basic)</mark>.

content:
  - title: Experience
    layout: list
    content:
      - layout: left
        border: weak
        title: Nicolet High School
        sub_title: IT Support Specialist
        caption: February 2022 - Present
        description: |
          I currently am in charge of the deployment and management of all Apple devices in the district, ensuring seamless integration and optimal performance for both staff and students.
          Leveraging Jamf Pro, I oversee the lifecycle of MacOS and iOS devices including automated enrollment, policy and profile management, application packaging and deployment, 
          task automation, and inventory management. 

          I also assist in the day to day operation of network support for all devices, as well as support for the various hardware that is utiziled in the district.
          More recently I have been working on learning the ins and out of our infrastructure, learning how to manage users, printers, etc in Active Directory, PaperCut, Google Admin, etc.

      - layout: left
        border: weak
        title: Rite Hite 
        sub_title: IT Support Specialist
        caption: September 2022 - January 2022
        description: |
          In this role, I was responsible for providing level 1 support to customers, staff service technicians, and employees. This support included troubleshooting and resolving
          issues for Windows based devices, Office 365, Salesforce, JDE Enteprise, Vizor/Airwatch asset tracking, MFP, etc. I also assisted in the deployment of new hardware and software
          license as needed as well.

          This was done utilizing our custome built knowledge base  and ticketing system, Team Viewer for remote sessions, and Active Directory for user management.

      - layout: left
        border: weak
        title: Rescue Dog Technology
        sub_title: Senior IT Technician
        caption: February 2021 - September 2022
        description: |
          In this role I was responsible for providing support and administration to a variety of clients in the Milwaukee area (some even as far as Boscobel, WI). 
          This included support for Windows and Mac devices, a host of different printers/MFPs, and network devices such as security cameras, print servers, etc. 
          I also assisted in training new technicians, answering escalated support tickets, and assisting in project work such as server migrations, network upgrades, etc.

          Having never worked for an MSP before, I learned a lot about how to manage multiple clients and their needs, as well as how to prioritize and manage my time effectively.

      - layout: left
        border: weak
        title: Pewaukee School District
        sub_title: Network Support Technician
        caption: August 2020 - February 2021
        description: |
          Being my first role back into IT after a five year hiatus, I was the part time network support tech for the district. My responsibilites included 
          providing support for staff and students devices. This included troubleshooting and resolving issues for Windows devices, Chromebooks, HP printers, Smartboards, etc.

          I was also solely responsible for managing our Jamf Pro instance for all district iPads. This included app procurement and deployment, policy and profile management,
    
      - layout: left
        border: weak
        title: F Street Hospitality
        sub_title: Executive Chef
        caption: July 2013 - August 2020
        description: |
          I started in the company as a hot line cook working part time while I was at Wauwatosa School District. I quickly was trained in all aspects of the kitchen and after
          a few years, I was offered the position of Sous Chef. My responsibilites increased to include ordering, menu planning for specials, and leading stations on busy nights of service. 
          After a few years in this role, I was promoted to Chef De Cuisine, where I gained more responsibilites including inventory management, scheduling, and leading the kitchen 
          in the absence of the Executive Chef. It was in 2019 that I was promoted to Executive Chef.

          This role was a great learning experience for me as I learned how to be a leader and manage a team, as well as operations and project management. I also fostered many relationships
          with people that are still in my life today.

      - layout: left
        title: Wauwatosa School District
        sub_title: Computer Support Specialist
        caption: August 2012 - August 2015
        description: |
          I was responsible for providing support and training dor staff and students across 7 different locations within the district. This included support for Windows and Mac devices, 
          thin clients, chromebooks, etc. I also assisted in project work including the deployment of new hardware and software, as well as the management of the districts inventory.

          Being my first position in a K-12 environment, I learned a lot about how to manage multiple locations and users, as well as how to coordinate and manage multiple issues effectively.

  - title: Education
    layout: list
    content:
      - title: University of Wisconsin - Milwaukee
        sub_title: BS - Information Science and Technology
        caption: 2007 - 2012
        description: |
          During my degree at UWM, I learned the basics of IT including networking, system administration & design, as well as basic programming (Python,
          Javascript, HTML/CSS, PHP). I also learned about the basics of project management and how to work in a team to deliver a successful projects and presentations.
          
          I also had the pleasure of working on campus for the Nurse Learning Resource Center in the school of nursing. My responsibilites included recording/indexing all student simulations,
          assisting with managing and upkeep of student computer lab, and repairing/maintaining simulation dolls and equipment.

  - title: When I'm Not Working
    layout: text
    content: | # this will include new lines to allow paragraphs
      When I'm not at work I enjoy spending time with my wife and our two cats, Milo and Thanos. 
      I also enjoy strength training and running. One of my current goals is to run the Milwaukee Half Marathon in April 2025 in sub 3 hours. 
      Some of my other interests include dining out at local restaurants, pretending I still can skateboard, and nerding out over sneakers and clothes.
      

# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

# sass:
#   style: compressed
